### ISSUE TITLE
allow both read and write for PafFile

### ISSUE THREAD

**Issue by bakerwm** [mbhall88/pafpy#4]
How to write the full records `PafRecord` to file? How about `mode={r,w}` argument?   (pafpy version: `0.1.2`)

I have a PAF record like this:

```
$ head -n 1 demo.paf
11737-1     294     89      294     -       31171-1     292     87      292     205     205     0       NM:i:0    ms:i:410        AS:i:410        nn:i:0  tp:A:S  cm:i:37 s1:i:193        de:f:0  rl:i:91 cg:Z:205M
```

Do something: (filtering, ...), and the tags are messed.

```python
# python
from pafpy import PafFile

with PafFile('demo.paf') as paf, open('demo.filtered.paf', 'wt') as w:
    for rec in paf:
        # do something
        print(str(rec), file=w)
        break
```

Tags values are missing in the output file: 

```
$ cat demo.filtered.paf
11737-1     294     89      294     -       31171-1     292     87      292     205     205     0       NMms      AS      nn      tp      cm      s1      de      rl      cg

```

**Comment by mbhall88** [comment]
Thanks for reporting this @bakerwm  - it was a silly mistake on my behalf that I had propagated in my tests also.

Version 0.1.3 should fix this now (please reopen if it doesn't).

In terms of how to write the full records, your method is the correct way
